version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ancient_free_will_postgres
    environment:
      POSTGRES_DB: ancient_free_will_db
      POSTGRES_USER: free_will_user
      POSTGRES_PASSWORD: free_will_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U free_will_user -d ancient_free_will_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ancient_free_will_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ancientfreewill.org
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
