version: '3.9'

services:
  # PostgreSQL 16 - Main relational database
  postgres:
    image: postgres:16-alpine
    container_name: ancient_free_will_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ancient_free_will_db
      POSTGRES_USER: free_will_user
      POSTGRES_PASSWORD: free_will_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      # Performance settings
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_WORK_MEM: 16MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"
    command: >
      postgres
      -c listen_addresses='*'
      -c log_statement=all
      -c log_destination=stderr
      -c logging_collector=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U free_will_user -d ancient_free_will_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ancient_free_will_network

  # Qdrant - Vector database for semantic search
  qdrant:
    image: qdrant/qdrant:v1.13.3
    container_name: ancient_free_will_qdrant
    restart: unless-stopped
    environment:
      # Qdrant configuration
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
      # Storage configuration
      QDRANT__STORAGE__STORAGE_PATH: /qdrant/storage
      # Performance settings optimized for 3072-dimensional embeddings
      QDRANT__SERVICE__MAX_REQUEST_SIZE_MB: 64
      QDRANT__SERVICE__MAX_WORKERS: 0  # Use all CPU cores
      # HNSW optimization for high-dimensional vectors
      QDRANT__STORAGE__OPTIMIZERS_CONFIG__INDEXING_THRESHOLD: 10000
      QDRANT__STORAGE__OPTIMIZERS_CONFIG__MEMMAP_THRESHOLD: 50000
      # Logging
      QDRANT__LOG_LEVEL: INFO
    volumes:
      - qdrant_data:/qdrant/storage
      - qdrant_snapshots:/qdrant/snapshots
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:6333/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ancient_free_will_network

  # PgAdmin - Database administration
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ancient_free_will_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ancientfreewill.org
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - ancient_free_will_network

# Persistent volumes
volumes:
  postgres_data:
    driver: local
    name: ancient_free_will_postgres_data
  qdrant_data:
    driver: local
    name: ancient_free_will_qdrant_data
  qdrant_snapshots:
    driver: local
    name: ancient_free_will_qdrant_snapshots
  pgadmin_data:
    driver: local
    name: ancient_free_will_pgadmin_data

# Network for service communication
networks:
  ancient_free_will_network:
    driver: bridge
    name: ancient_free_will_network
