"""Tag translation-provenance on English passage kg_nodes.

Per project memory, ~2952 ``_en`` passage nodes were generated by a
``gemini-2.5-flash-batch`` run and carry ``source_model`` in metadata.
None of them currently flag ``translation_source`` so a downstream
reader cannot distinguish an AI batch from a published translation.

This audit:

1. For every passage kg_node where ``node_id LIKE '%_en'`` and
   ``language == 'eng'``, set ``metadata.translation_source =
   'AI batch: <source_model>'`` and ``metadata.translation_type =
   'machine'`` if not already set.
2. For passage kg_nodes whose description contains
   ``Based on <X>`` in metadata.translation_source, leave them alone
   (those are human-revised). They were already tagged correctly.
3. For non-_en passages with language='eng' but no provenance, flag
   ``needs_translation_provenance = true``.

This is one-way enrichment -- mechanical, no scholarly judgement
required. Idempotent.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from typing import Any

import asyncpg
from _common import REPORTS_DIR, connect, emit_summary, normalize_meta, write_jsonl


async def audit(conn: asyncpg.Connection) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []

    # 1) _en suffix nodes
    rows = await conn.fetch(
        "SELECT node_id, metadata FROM free_will.kg_nodes "
        "WHERE type='passage' AND node_id LIKE '%_en'"
    )
    for row in rows:
        node_id = row["node_id"]
        metadata = normalize_meta(row["metadata"])
        existing_source = metadata.get("translation_source")
        if existing_source:
            continue
        source_model = metadata.get("source_model")
        provenance = (
            f"AI batch: {source_model}" if source_model else "AI batch (unknown model)"
        )
        findings.append(
            {
                "node_id": node_id,
                "dimension": "translation_provenance",
                "issue": "missing_translation_source_on_ai_batch",
                "current": {
                    "source_model": source_model,
                    "translation_source": existing_source,
                },
                "suggested_fix": {
                    "set_metadata": {
                        "translation_source": provenance,
                        "translation_type": "machine",
                    }
                },
                "confidence": 1.0,
                "auto_apply": True,
            }
        )

    # 2) English passage nodes lacking _en suffix but with language='eng'
    rows = await conn.fetch(
        "SELECT node_id, metadata FROM free_will.kg_nodes "
        "WHERE type='passage' AND metadata->>'language' = 'eng' "
        "  AND node_id NOT LIKE '%_en' "
        "  AND NOT (metadata ? 'translation_source')"
    )
    for row in rows:
        node_id = row["node_id"]
        findings.append(
            {
                "node_id": node_id,
                "dimension": "translation_provenance",
                "issue": "english_passage_missing_provenance",
                "current": None,
                "suggested_fix": {
                    "set_metadata": {"needs_translation_provenance": True}
                },
                "confidence": 1.0,
                "auto_apply": True,
            }
        )

    return findings


async def apply_fixes(conn: asyncpg.Connection, findings: list[dict[str, Any]]) -> int:
    applied = 0
    for f in findings:
        if not f.get("auto_apply"):
            continue
        node_id = f["node_id"]
        fix = f["suggested_fix"].get("set_metadata", {})
        if not fix:
            continue
        row = await conn.fetchrow(
            "SELECT metadata FROM free_will.kg_nodes WHERE node_id=$1", node_id
        )
        if row is None:
            continue
        metadata = normalize_meta(row["metadata"])
        for k, v in fix.items():
            metadata[k] = v
        await conn.execute(
            "UPDATE free_will.kg_nodes SET metadata=$2::jsonb, updated_at=now() WHERE node_id=$1",
            node_id,
            json.dumps(metadata, ensure_ascii=False),
        )
        applied += 1
    return applied


async def amain(args: argparse.Namespace) -> int:
    conn = await connect()
    try:
        findings = await audit(conn)
        report_path = REPORTS_DIR / "translation_provenance_report.jsonl"
        write_jsonl(findings, report_path)

        by_issue: dict[str, int] = {}
        auto = 0
        for f in findings:
            by_issue[f["issue"]] = by_issue.get(f["issue"], 0) + 1
            if f["auto_apply"]:
                auto += 1
        counts = {
            "total_findings": len(findings),
            "auto_apply_pending": auto,
            **{f"issue.{k}": v for k, v in sorted(by_issue.items())},
        }
        emit_summary("translation_provenance", counts)
        print(f"[translation_provenance] wrote {report_path}", file=sys.stderr)

        if args.apply:
            applied = await apply_fixes(conn, findings)
            print(f"[translation_provenance] applied {applied} nodes", file=sys.stderr)
    finally:
        await conn.close()
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit translation provenance")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    return asyncio.run(amain(args))


if __name__ == "__main__":
    sys.exit(main())
