-- G14 corpus tamper-evidence + edition provenance.
--
-- Adds:
--   1. free_will.passages.text_sha256   TEXT  (nullable) — SHA-256 hex digest of
--      the NFC-normalized text_content, computed at ingest time. Canonical
--      hashing lives in eleutheria_database.services.text_integrity (text_sha256);
--      the drift auditor is database/scripts/philological_audit/audit_text_drift.py.
--   2. free_will.passages.text_provenance JSONB (nullable) — edition provenance
--      (see docs/operations/corpus-integrity.md for the schema). Backfill SQL is
--      generated by database/scripts/generate_text_provenance_backfill.py and
--      reviewed manually before being applied.
--   3. Defensive hardening on free_will.passage_citations:
--      - FK kg_node_id -> kg_nodes(node_id), added NOT VALID (existing orphan
--        citations do not block the migration; validate later, see below).
--      - UNIQUE (passage_id, kg_node_id, citation_type) via a guarded unique
--        index — created only when no duplicates exist.
--   4. Guarded UNIQUE (work_id, canonical_ref) on free_will.passages, partial
--      on passage_role = 'original' (translations/paraphrases legitimately
--      share the canonical_ref of their source passage).
--
-- NOTE on existing constraints (checked against database/schema/schema.sql):
--   * passage_citations.passage_id already has FK -> passages ON DELETE CASCADE.
--   * passage_citations.kg_node_id is TEXT NOT NULL with NO FK — added here.
--   * passage_citations has NO unique constraint — added here (guarded).
--   * passages has NO unique constraint on (work_id, canonical_ref) — added
--     here as a guarded partial unique index.
--
-- Transaction-safety: every statement is plain DDL or a DO block — no
-- CREATE INDEX CONCURRENTLY, no explicit COMMIT — so the whole file runs as
-- one implicit transaction under database/scripts/apply_schema.py.
-- Requires PostgreSQL 15+ (UNIQUE ... NULLS NOT DISTINCT); Supabase qualifies.
--
-- ---------------------------------------------------------------------------
-- PRE-CHECK QUERIES — run these manually BEFORE applying; the guarded blocks
-- below skip (with a WARNING in server logs) instead of failing when data
-- would violate a constraint, but you want to know the answer in advance:
--
--   -- (a) duplicate original passages that would block UNIQUE(work_id, canonical_ref):
--   SELECT work_id, canonical_ref, COUNT(*)
--   FROM free_will.passages
--   WHERE passage_role = 'original'
--   GROUP BY 1, 2 HAVING COUNT(*) > 1;
--
--   -- (b) duplicate citations that would block the citations unique index:
--   SELECT passage_id, kg_node_id, citation_type, COUNT(*)
--   FROM free_will.passage_citations
--   GROUP BY 1, 2, 3 HAVING COUNT(*) > 1;
--
--   -- (c) orphan kg_node_id values (tolerated by NOT VALID until VALIDATE):
--   SELECT pc.kg_node_id, COUNT(*)
--   FROM free_will.passage_citations pc
--   LEFT JOIN free_will.kg_nodes n ON n.node_id = pc.kg_node_id
--   WHERE n.node_id IS NULL
--   GROUP BY 1 ORDER BY 2 DESC;
--
-- POST-MIGRATION (separate session, after (c) returns zero rows / is repaired):
--   ALTER TABLE free_will.passage_citations
--       VALIDATE CONSTRAINT fk_passage_citations_kg_node_id;
-- ---------------------------------------------------------------------------

-- 1. Tamper-evidence + provenance columns (nullable; backfilled separately).
ALTER TABLE free_will.passages
    ADD COLUMN IF NOT EXISTS text_sha256 TEXT;

ALTER TABLE free_will.passages
    ADD COLUMN IF NOT EXISTS text_provenance JSONB;

-- Shape guard on the digest (NOT VALID: all existing rows are NULL anyway,
-- and a CHECK added NOT VALID avoids a full-table verification scan).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_passages_text_sha256_format'
          AND conrelid = 'free_will.passages'::regclass
    ) THEN
        ALTER TABLE free_will.passages
            ADD CONSTRAINT chk_passages_text_sha256_format
            CHECK (text_sha256 IS NULL OR text_sha256 ~ '^[0-9a-f]{64}$')
            NOT VALID;
    END IF;
END $$;

-- 2. FK hardening: passage_citations.kg_node_id -> kg_nodes(node_id).
--    NOT VALID so pre-existing orphans don't abort the transaction; the
--    default NO ACTION (no CASCADE) is deliberate: deleting a KG node with
--    live citations must fail loudly, not silently drop scholarly anchors.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_passage_citations_kg_node_id'
          AND conrelid = 'free_will.passage_citations'::regclass
    ) THEN
        ALTER TABLE free_will.passage_citations
            ADD CONSTRAINT fk_passage_citations_kg_node_id
            FOREIGN KEY (kg_node_id) REFERENCES free_will.kg_nodes(node_id)
            NOT VALID;
    END IF;
END $$;

-- 3. UNIQUE hardening: one citation per (passage, node, type).
--    NULLS NOT DISTINCT so two rows with citation_type NULL also collide.
--    Guarded: skipped with a WARNING when duplicates already exist
--    (adjudicate them manually — never auto-deduplicate scholarly data).
DO $$
DECLARE
    dup_count BIGINT;
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'free_will'
          AND indexname = 'uq_passage_citations_passage_node_type'
    ) THEN
        RETURN;
    END IF;

    SELECT COUNT(*) INTO dup_count FROM (
        SELECT 1
        FROM free_will.passage_citations
        GROUP BY passage_id, kg_node_id, citation_type
        HAVING COUNT(*) > 1
    ) d;

    IF dup_count = 0 THEN
        CREATE UNIQUE INDEX uq_passage_citations_passage_node_type
            ON free_will.passage_citations (passage_id, kg_node_id, citation_type)
            NULLS NOT DISTINCT;
    ELSE
        RAISE WARNING
            'skipping uq_passage_citations_passage_node_type: % duplicate (passage_id, kg_node_id, citation_type) group(s) — run pre-check (b) and adjudicate manually',
            dup_count;
    END IF;
END $$;

-- 4. UNIQUE (work_id, canonical_ref) on passages — partial on originals.
--    Translation/paraphrase rows (passage_role <> 'original') share their
--    source passage's canonical_ref by design, so a full unique constraint
--    would be wrong. Guarded: skipped with a WARNING when duplicates exist.
DO $$
DECLARE
    dup_count BIGINT;
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'free_will'
          AND indexname = 'uq_passages_work_canonical_ref_original'
    ) THEN
        RETURN;
    END IF;

    SELECT COUNT(*) INTO dup_count FROM (
        SELECT 1
        FROM free_will.passages
        WHERE passage_role = 'original'
        GROUP BY work_id, canonical_ref
        HAVING COUNT(*) > 1
    ) d;

    IF dup_count = 0 THEN
        CREATE UNIQUE INDEX uq_passages_work_canonical_ref_original
            ON free_will.passages (work_id, canonical_ref)
            WHERE passage_role = 'original';
    ELSE
        RAISE WARNING
            'skipping uq_passages_work_canonical_ref_original: % duplicate (work_id, canonical_ref) group(s) among originals — run pre-check (a) and adjudicate manually',
            dup_count;
    END IF;
END $$;

-- Lookup support for the drift auditor (plain index — 69k rows, fast inline).
CREATE INDEX IF NOT EXISTS idx_passages_text_sha256
    ON free_will.passages (text_sha256)
    WHERE text_sha256 IS NOT NULL;
