#!/usr/bin/env python3
"""Decisions on the 96 rows of c1_passage_concepts/queue_contradictions.csv.

Each row is an existing passage -> concept link that Jev contradicts. For
Alexander's De fato the test is run on the complete chapter of the First1KGreek
TEI (Bruns 1892), not on the stored text: a link is withdrawn only when its own
rationale names a term that the chapter does not contain.

Tuples: (passage_id, concept_id, jev_p, verdict, note).
"""

TEI = "data/tlg0732/tlg014/tlg0732.tlg014.1st1K-grc1.xml"
TEI_SHA256 = "184b01f38061cfa00b276ed8d9580f3f842f564856851e4bcc124adcc2edbb2f"
TEI_COMMIT = "8ee111eb44ecef4120c844e10749178d95d1f30c"  # OpenGreekAndLatin/First1KGreek

DECISIONS = [
    ('passage_alex_fat_5', 'concept_plurality_goods_alex', 0.02, 'remove', 'The edge rationale names the term, and it is absent from the complete chapter (First1KGreek TEI, Bruns 1892): ηδυ: 0, ηδον: 0, συμφερ: 0.'),
    ('passage_aug_lib_arb_2_16_44', 'concept_liberum_arbitrium_u3v4w5x6', 0.03, 'remove', 'auto_generated whole-work wiring; the passage belongs to the Book II proof of God from immutable truth (number, wisdom, truth), as its own summary shows.'),
    ('passage_alex_fat_25', 'concept_logos_krites_alex', 0.04, 'needs_romain', 'Conceptual rationale; its key term is absent from the complete chapter (κριτ: 0, κρισ: 0, κριν: 0), which does not by itself refute the link.'),
    ('passage_aug_lib_arb_2_16_44', 'concept_voluntas_y7z8a9b0', 0.04, 'remove', 'auto_generated whole-work wiring; the passage belongs to the Book II proof of God from immutable truth (number, wisdom, truth), as its own summary shows.'),
    ('passage_aug_lib_arb_2_11_31', 'concept_voluntas_y7z8a9b0', 0.04, 'remove', 'auto_generated whole-work wiring; the passage belongs to the Book II proof of God from immutable truth (number, wisdom, truth), as its own summary shows.'),
    ('passage_alex_fat_27', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.04, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_alex_fat_13', 'concept_hegemonikon_stoic', 0.05, 'needs_romain', 'Conceptual rationale; its key term is absent from the complete chapter (ηγεμον: 0), which does not by itself refute the link.'),
    ('passage_alex_fat_32', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.05, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_alex_fat_3', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.05, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_alex_fat_26', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.05, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_alex_fat_33', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.05, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_aug_lib_arb_2_13_35', 'concept_liberum_arbitrium_u3v4w5x6', 0.05, 'remove', 'auto_generated whole-work wiring; the passage belongs to the Book II proof of God from immutable truth (number, wisdom, truth), as its own summary shows.'),
    ('passage_alex_fat_27', 'concept_divine_prescience', 0.05, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): προνοι: 2, προγν: 0.'),
    ('passage_aug_lib_arb_2_18_50', 'concept_voluntas_y7z8a9b0', 0.06, 'false_positive', 'II.18.50 opens the discussion of free will as a middle good (virtues cannot be misused, free choice can); kept.'),
    ('passage_alex_fat_3', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.06, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_12', 'concept_tuche_chance_alex', 0.06, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): τυχη: 2.'),
    ('passage_alex_fat_15', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.06, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_aug_lib_arb_2_11_31', 'concept_liberum_arbitrium_u3v4w5x6', 0.06, 'remove', 'auto_generated whole-work wiring; the passage belongs to the Book II proof of God from immutable truth (number, wisdom, truth), as its own summary shows.'),
    ('passage_alex_fat_8', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.07, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_alex_fat_23', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.08, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_aug_lib_arb_2_18_50', 'concept_liberum_arbitrium_u3v4w5x6', 0.09, 'false_positive', 'II.18.50 opens the discussion of free will as a middle good (virtues cannot be misused, free choice can); kept.'),
    ('passage_alex_fat_25', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.09, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_alex_fat_14', 'concept_four_categories_alex', 0.09, 'needs_romain', 'Conceptual link (no key term to test); not decidable from the text alone.'),
    ('passage_alex_fat_4', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.09, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_25', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.1, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_9', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.1, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_alex_fat_15', 'concept_external_principle_action', 0.1, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): εξωθεν: 5.'),
    ('passage_alex_fat_22', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.1, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_alex_fat_35', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.1, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_31', 'concept_hypothetical_fate_middle_platonist', 0.11, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): υποθεσ: 2.'),
    ('passage_alex_fat_19', 'concept_tuche_chance_alex', 0.11, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): τυχη: 2.'),
    ('passage_alex_fat_18', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.12, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_alex_fat_3', 'concept_non_necessitating_cause_alex', 0.12, 'needs_romain', 'Conceptual link (no key term to test); not decidable from the text alone.'),
    ('passage_alex_fat_25', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.12, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_alex_fat_9', 'concept_kyrios_alex', 0.13, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): κυρι: 1.'),
    ('passage_alex_fat_14', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.13, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_4', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.13, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_alex_fat_23', 'concept_divine_prescience', 0.13, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): προνοι: 1, προγν: 0.'),
    ('passage_aug_lib_arb_2_16_43', 'concept_liberum_arbitrium_u3v4w5x6', 0.13, 'needs_romain', 'Book II proof of God, but on loving the signs instead of what they signify; the will may be at issue.'),
    ('passage_alex_fat_8', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.14, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_31', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.14, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_arist_en_3_1', 'concept_akousion_involuntary_aristotle_b2c3d4e5', 0.14, 'false_positive', 'Nicomachean Ethics III.1 and III.5 are the loci of the voluntary and the involuntary; kept.'),
    ('passage_alex_fat_2', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.14, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_36', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.14, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_30', 'concept_hypothetical_fate_middle_platonist', 0.14, 'needs_romain', 'Conceptual rationale; its key term is absent from the complete chapter (υποθεσ: 0), which does not by itself refute the link.'),
    ('passage_alex_fat_13', 'concept_external_principle_action', 0.15, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): εξωθεν: 2.'),
    ('passage_alex_fat_13', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.15, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_33', 'concept_logos_krites_alex', 0.15, 'needs_romain', 'Conceptual rationale; its key term is absent from the complete chapter (κριτ: 0, κρισ: 0, κριν: 0), which does not by itself refute the link.'),
    ('passage_alex_fat_14', 'concept_exousia_alex', 0.15, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): εξουσι: 3.'),
    ('passage_alex_fat_29', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.16, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_alex_fat_13', 'concept_cylinder_analogy_chrysippus_e5f6g7h8', 0.17, 'needs_romain', 'Conceptual rationale; its key term is absent from the complete chapter (κυλινδ: 0), which does not by itself refute the link.'),
    ('passage_alex_fat_18', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.17, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_12', 'concept_four_categories_alex', 0.17, 'needs_romain', 'Conceptual link (no key term to test); not decidable from the text alone.'),
    ('passage_alex_fat_19', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.17, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_6', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.17, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_alex_fat_13', 'concept_synkatathesis_logike_alex', 0.18, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): συγκαταθ: 1.'),
    ('passage_alex_fat_25', 'concept_causal_asymmetry_alex', 0.18, 'needs_romain', 'Conceptual link (no key term to test); not decidable from the text alone.'),
    ('passage_alex_fat_34', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.18, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_22', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.18, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_33', 'concept_synkatathesis_logike_alex', 0.19, 'needs_romain', 'Conceptual rationale; its key term is absent from the complete chapter (συγκαταθ: 0), which does not by itself refute the link.'),
    ('passage_aug_lib_arb_2_13_35', 'concept_voluntas_y7z8a9b0', 0.19, 'remove', 'auto_generated whole-work wiring; the passage belongs to the Book II proof of God from immutable truth (number, wisdom, truth), as its own summary shows.'),
    ('passage_alex_fat_34', 'concept_four_categories_alex', 0.19, 'needs_romain', 'Conceptual link (no key term to test); not decidable from the text alone.'),
    ('passage_alex_fat_26', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.2, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_17', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.2, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_33', 'concept_hegemonikon_stoic', 0.2, 'needs_romain', 'Conceptual rationale; its key term is absent from the complete chapter (ηγεμον: 0), which does not by itself refute the link.'),
    ('passage_alex_fat_20', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.2, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_alex_fat_30', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.2, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_alex_fat_20', 'concept_inner_freedom_alex', 0.21, 'needs_romain', 'Conceptual link (no key term to test); not decidable from the text alone.'),
    ('passage_alex_fat_35', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.21, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_alex_fat_8', 'concept_four_categories_alex', 0.22, 'needs_romain', 'Conceptual link (no key term to test); not decidable from the text alone.'),
    ('passage_alex_fat_2', 'concept_tuche_chance_alex', 0.22, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): τυχη: 1.'),
    ('passage_alex_fat_20', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.22, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_10', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.22, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_alex_fat_19', 'concept_plurality_goods_alex', 0.23, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): ηδυ: 0, ηδον: 1, συμφερ: 0.'),
    ('passage_alex_fat_37', 'concept_tuche_chance_alex', 0.24, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): τυχη: 1.'),
    ('passage_alex_fat_37', 'concept_eph_hemin_two_sided_potestative', 0.24, 'needs_romain', 'Conceptual link (no key term to test); not decidable from the text alone.'),
    ('passage_alex_fat_12', 'concept_inner_freedom_alex', 0.24, 'needs_romain', 'Conceptual link (no key term to test); not decidable from the text alone.'),
    ('passage_alex_fat_38', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.24, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_24', 'concept_kyrios_alex', 0.24, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): κυρι: 2.'),
    ('passage_alex_fat_28', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.24, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_alex_fat_24', 'concept_tuche_chance_alex', 0.25, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): τυχη: 1.'),
    ('passage_alex_fat_11', 'concept_heimarmene_fate_stoics_j0k1l2m3', 0.25, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ειμαρμ: 0).'),
    ('passage_alex_fat_39', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.26, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_9', 'concept_tuche_chance_alex', 0.26, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): τυχη: 1.'),
    ('passage_alex_fat_28', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.26, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_8', 'concept_kyrios_alex', 0.27, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): κυρι: 2.'),
    ('passage_alex_fat_31', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.27, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_alex_fat_9', 'concept_eph_hemin_in_our_power_aristotle_d4e5f6g7', 0.27, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (εφημιν: 0).'),
    ('passage_aug_lib_arb_2_16_43', 'concept_voluntas_y7z8a9b0', 0.27, 'needs_romain', 'Book II proof of God, but on loving the signs instead of what they signify; the will may be at issue.'),
    ('passage_alex_fat_31', 'concept_saving_teaching_alex', 0.28, 'remove', 'The edge rationale names the term, and it is absent from the complete chapter (First1KGreek TEI, Bruns 1892): διδασκαλ: 0.'),
    ('passage_alex_fat_20', 'concept_boule_practical_wisdom', 0.28, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): βουλ: 1.'),
    ('passage_alex_fat_30', 'concept_boule_practical_wisdom', 0.29, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): βουλ: 2.'),
    ('passage_alex_fat_5', 'concept_endechomenon_contingent_aristotle_e5f6g7h8', 0.3, 'needs_romain', 'auto_generated without rationale; key term absent from the complete chapter (ενδεχ: 0).'),
    ('passage_alex_fat_31', 'concept_boule_practical_wisdom', 0.3, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): βουλ: 4.'),
    ('passage_alex_fat_1', 'concept_prohairesis_alex', 0.3, 'false_positive', 'The stem of the concept occurs in the complete chapter (First1KGreek TEI, Bruns 1892): προαιρ: 1.'),
    ('passage_aristotle_en_iii_5_1114b1', 'concept_hekousion_voluntary_aristotle_a1b2c3d4', 0.3, 'false_positive', 'Nicomachean Ethics III.1 and III.5 are the loci of the voluntary and the involuntary; kept.'),
]
