#!/usr/bin/env python3
"""Cicero structural fix: re-ground arguments, delete fake passage-shells + bogus works.

Background
----------
122 KG passage-shell nodes ``passage_cic_div_*`` (100) + ``passage_cic_nat_deor_*``
(22) were ingested from the WRONG corpus slots: Cicero *Topica* (phi042) and
*Orator* (phi041). Their stored text is Topica/Orator prose and the trailing "N"
is a Topica/Orator section index, NOT a genuine *De Divinatione* / *De Natura
Deorum* locus. They carry structural edges (122 ``authored_by`` to Cicero, 122
``part_of`` to the De Div / De Nat Deorum KG work nodes) and are referenced by
~11 Carneadean arguments via 49 ``cites_primary_source`` + 1 ``evidenced_by``
edges. Their ``passage_citations`` (type ``snapshot_passage_node``) point at the
Topica/Orator passages.

The genuine works are correctly ingested:
  - De Divinatione   urn_cts_latinlit_phi0474_phi053_lat  (refs 1.1 .. 2.150)
  - De Natura Deorum urn_cts_latinlit_phi0474_phi050_lat  (refs 1.1 .. 3.95)

Three phases (dry-run by default; --commit to mutate; --phase to select)
-----------------------------------------------------------------------
PHASE A — re-ground the arguments
  For each argument whose description names explicit De Div / De Nat Deorum loci
  (single sections AND ranges), create a ``passage_citations`` row linking the
  GENUINE corpus passage at that ref to the ARGUMENT node
  (citation_type='primary_source'). ZERO fabrication: only loci the argument
  explicitly states are used. Arguments naming no Cicero locus are skipped.
  Also deletes the one stale bogus Topica ``evidenced_by`` citation that
  argument_cicero_de_div_anti_mantike_amand1945 still carries (superseded by its
  genuine 2.21 primary_source citation).

PHASE B — delete the fake shells (everywhere)
  Delete the 122 shells' ``passage_citations`` rows, their ``kg_edges`` rows (all
  294 relations), and their ``kg_nodes`` rows in the DB; remove the same node
  lines from data/kg/nodes.jsonl and edge lines from data/kg/edges.jsonl.

PHASE C — drop the bogus Topica/Orator works
  After Phase B, confirm 0 remaining ``passage_citations`` on the phi042/phi041
  passages, then delete their passages + ancient_works rows. STOP if any citation
  remains.

Sync rule: KG git mirror (data/kg/*.jsonl) is edited DIRECTLY (the API exporter
lags); corpus snapshot (data/corpus/{passages,citations}.jsonl) is regenerated by
scripts.export_corpus_snapshot after this script.

Usage:
    .venv/bin/python -m scripts.fix_cicero_structural_2026_05_25 [--phase A|B|C|all] [--commit]

Dependencies: asyncpg (DATABASE_URL from .env). lxml not used here.
"""

from __future__ import annotations

import argparse
import asyncio
import json
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import asyncpg

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT_DIR = (
    ROOT / "data" / "corpus" / "fix_snapshots" / "fix_cicero_structural_2026_05_25"
)
NODES_PATH = ROOT / "data" / "kg" / "nodes.jsonl"
EDGES_PATH = ROOT / "data" / "kg" / "edges.jsonl"

DIV_CANONICAL = "urn_cts_latinlit_phi0474_phi053_lat"  # De Divinatione (genuine)
NATDEOR_CANONICAL = "urn_cts_latinlit_phi0474_phi050_lat"  # De Natura Deorum (genuine)
TOPICA_CANONICAL = (
    "urn_cts_latinlit_phi0474_phi042_lat"  # bogus "De Divinatione" (= Topica)
)
ORATOR_CANONICAL = (
    "urn_cts_latinlit_phi0474_phi041_lat"  # bogus "De Natura Deorum" (= Orator)
)

SHELL_LIKE = ("passage_cic_div_%", "passage_cic_nat_deor_%")


# ---------------------------------------------------------------------------
# PHASE A re-grounding plan.
#
# Each argument -> (genuine_work_canonical, [explicit canonical_refs], confidence,
# provenance note). ONLY loci the argument explicitly names in its own
# description are listed (single sections expanded from ranges). Arguments that
# name no Cicero locus are intentionally absent (recorded in SKIPPED_ARGS).
# ---------------------------------------------------------------------------
def _expand(*parts: object) -> list[str]:
    """Expand book.section specs into canonical_refs.

    Accepts ints/strs for single sections ("2.97") and (book, start, end) tuples
    for inclusive ranges within one book ("2", 9, 72 -> 2.9 .. 2.72).
    """
    out: list[str] = []
    for p in parts:
        if isinstance(p, tuple):
            book, start, end = p
            out.extend(f"{book}.{s}" for s in range(start, end + 1))
        else:
            out.append(str(p))
    # dedupe preserving order
    seen: set[str] = set()
    deduped: list[str] = []
    for r in out:
        if r not in seen:
            seen.add(r)
            deduped.append(r)
    return deduped


REGROUND_PLAN: dict[str, dict] = {
    # "De div. livre II, paragraphes 3, 9 à 72, 148"
    "argument_carneadean_anti_mantike_amand1945": {
        "work": DIV_CANONICAL,
        "refs": _expand("2.3", ("2", 9, 72), "2.148"),
        "confidence": 0.7,
        "note": "Amand 1945: 'Cicéron De divinatione livre II (paragraphes 3, 9 à 72, 148)'.",
    },
    # "Cicéron De div. II.47.97 sur Cannes"
    "argument_carneadean_antiastrological_collective_death_amand1945": {
        "work": DIV_CANONICAL,
        "refs": _expand("2.97"),
        "confidence": 0.85,
        "note": "Amand 1945: 'Cicéron De div. II.47.97 sur Cannes' (Cannae case at De Div 2.97).",
    },
    # "transmise par Cicéron De div. II.46.96-97"
    "argument_carneadean_antiastrological_nomima_barbarika_amand1945": {
        "work": DIV_CANONICAL,
        "refs": _expand("2.96", "2.97"),
        "confidence": 0.8,
        "note": "Amand 1945: nomima barbarika 'transmise par Cicéron De div. II.46.96-97'.",
    },
    # label + desc: "De divinatione II, 8, 21"
    "argument_cicero_de_div_anti_mantike_amand1945": {
        "work": DIV_CANONICAL,
        "refs": _expand("2.21"),
        "confidence": 0.85,
        "note": "Argument label/desc: 'Cicéron De divinatione II, 8, 21' (Stoic-divination dilemma).",
    },
    # "Amand rapproche cet argument de Ciceron De div. II.7.19-9.24"
    "argument_diodore_tarsus_impossibility_prediction_carneadean": {
        "work": DIV_CANONICAL,
        "refs": _expand(("2", 19, 24)),
        "confidence": 0.7,
        "note": "Amand 1945 rapprochement: 'Cicéron De div. II.7.19-9.24'.",
    },
    # "traité plus complètement par Cicéron De natura deorum livre III"
    "argument_carneadean_anti_teleology_cosmos_amand1945": {
        "work": NATDEOR_CANONICAL,
        "refs": None,  # whole book III -> resolved dynamically to 3.1 .. 3.95
        "book": "3",
        "confidence": 0.6,
        "note": "Amand 1945: anti-teleology 'traité plus complètement par Cicéron De natura deorum livre III' (whole book 3).",
    },
}

# Arguments that cite a shell but name NO explicit Cicero locus -> not grounded
# to Cicero (would require fabricating a citation the source does not make).
SKIPPED_ARGS: dict[str, str] = {
    "argument_carneadean_antiastrological_horoscope_impossibility_amand1945": "Desc cites Amand p.49-51 only; names no De Div/De Nat Deorum section.",
    "argument_carneadean_antiastrological_twins_amand1945": "Desc cites Augustine De civ. dei V.1 + Bouché-Leclercq; names no Cicero section.",
    "argument_carneadean_antiastrological_animals_amand1945": "Desc cites Augustine De civ. dei V.7, Aulus Gellius XIV.1.31, Diodore; names no Cicero section.",
    "argument_basil_observation_impossible_at_birth": "Basil Hex VI.5 (PG 29) + Sextus/Origen; names no Cicero section.",
    "argument_basil_kings_born_daily": "Basil Hex VI.7 (PG 29) + Ptolemy; names no Cicero section.",
}

# Stale bogus citation to remove in Phase A (the arg's own evidenced_by row that
# still points at the Topica slot, superseded by its genuine 2.21 primary_source).
STALE_BOGUS_ARG_CITATION = "argument_cicero_de_div_anti_mantike_amand1945"


def _db_url() -> str:
    for line in (ROOT / ".env").open(encoding="utf-8"):
        if line.startswith("DATABASE_URL="):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    raise SystemExit("DATABASE_URL not found in .env")


def _pg_url(url: str) -> str:
    if url.startswith("postgresql://"):
        return "postgres://" + url[len("postgresql://") :]
    return url


def _stamp() -> str:
    return datetime.now(UTC).isoformat()


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------
async def _work_id(conn: asyncpg.Connection, canonical_id: str) -> str | None:
    wid: str | None = await conn.fetchval(
        "SELECT work_id::text FROM free_will.ancient_works WHERE canonical_id = $1",
        canonical_id,
    )
    return wid


async def _passage_id_for_ref(
    conn: asyncpg.Connection, work_id: str, ref: str
) -> str | None:
    pid: str | None = await conn.fetchval(
        "SELECT passage_id::text FROM free_will.passages WHERE work_id = $1::uuid AND canonical_ref = $2",
        work_id,
        ref,
    )
    return pid


async def _book_refs(
    conn: asyncpg.Connection, work_id: str, book: str
) -> list[tuple[str, str]]:
    rows = await conn.fetch(
        "SELECT passage_id::text AS pid, canonical_ref FROM free_will.passages "
        "WHERE work_id = $1::uuid AND canonical_ref LIKE $2 ORDER BY sequence_number",
        work_id,
        f"{book}.%",
    )
    return [(r["pid"], r["canonical_ref"]) for r in rows]


async def _shell_ids(conn: asyncpg.Connection) -> list[str]:
    rows = await conn.fetch(
        "SELECT node_id FROM free_will.kg_nodes "
        "WHERE node_id LIKE $1 OR node_id LIKE $2 ORDER BY node_id",
        *SHELL_LIKE,
    )
    return [r["node_id"] for r in rows]


# ---------------------------------------------------------------------------
# git mirror editing
# ---------------------------------------------------------------------------
def _git_node_id(obj: dict) -> str:
    return obj.get("id") or obj.get("node_id") or ""


def _git_edge_ends(obj: dict) -> tuple[str, str, str]:
    s = obj.get("source") or obj.get("source_id") or obj.get("source_node_id") or ""
    t = obj.get("target") or obj.get("target_id") or obj.get("target_node_id") or ""
    r = obj.get("relation") or obj.get("edge_type") or ""
    return s, t, r


def _remove_git_lines(
    path: Path, drop_predicate: Callable[[dict], bool], commit: bool
) -> int:
    """Rewrite a JSONL file dropping lines for which predicate(obj) is True.

    Returns count of dropped lines. Byte-for-byte preserves surviving lines
    (writes original line text, not a re-serialization) so unrelated rows are
    untouched. Atomic replace via .tmp.
    """
    kept: list[str] = []
    dropped = 0
    with path.open(encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            obj = json.loads(line)
            if drop_predicate(obj):
                dropped += 1
            else:
                kept.append(line if line.endswith("\n") else line + "\n")
    if commit and dropped:
        tmp = path.with_suffix(path.suffix + ".tmp")
        with tmp.open("w", encoding="utf-8") as f:
            f.writelines(kept)
        tmp.replace(path)
    return dropped


# ---------------------------------------------------------------------------
# PHASE A
# ---------------------------------------------------------------------------
async def phase_a(conn: asyncpg.Connection, commit: bool, ts: str) -> dict:
    print("\n" + "=" * 70)
    print("PHASE A — re-ground arguments to genuine De Div / De Nat Deorum")
    print("=" * 70)

    # Resolve work_ids
    work_ids: dict[str, str] = {}
    for canon in (DIV_CANONICAL, NATDEOR_CANONICAL):
        wid = await _work_id(conn, canon)
        if not wid:
            raise SystemExit(f"Genuine work {canon} not found in ancient_works")
        work_ids[canon] = wid

    # Build the citation plan: (passage_id, ref, arg, confidence, note)
    plan: list[dict] = []
    missing: list[str] = []
    for arg, spec in REGROUND_PLAN.items():
        wid = work_ids[spec["work"]]
        if spec.get("refs") is None:
            # whole book
            refs_pids = await _book_refs(conn, wid, spec["book"])
        else:
            refs_pids = []
            for ref in spec["refs"]:
                pid = await _passage_id_for_ref(conn, wid, ref)
                if pid is None:
                    missing.append(
                        f"{arg}: {spec['work']} {ref} (genuine passage absent)"
                    )
                    continue
                refs_pids.append((pid, ref))
        for pid, ref in refs_pids:
            plan.append(
                {
                    "arg": arg,
                    "work": spec["work"],
                    "ref": ref,
                    "passage_id": pid,
                    "confidence": spec["confidence"],
                    "note": spec["note"],
                }
            )

    # Idempotency: which (arg, passage_id) primary_source citations already exist?
    existing_pairs: set[tuple[str, str]] = set()
    args_in_plan = sorted({p["arg"] for p in plan})
    if args_in_plan:
        rows = await conn.fetch(
            "SELECT kg_node_id, passage_id::text AS pid FROM free_will.passage_citations "
            "WHERE kg_node_id = ANY($1::text[]) AND citation_type = 'primary_source'",
            args_in_plan,
        )
        existing_pairs = {(r["kg_node_id"], r["pid"]) for r in rows}

    to_create = [p for p in plan if (p["arg"], p["passage_id"]) not in existing_pairs]
    already = len(plan) - len(to_create)

    # Stale bogus citation to delete (arg evidenced_by -> Topica passage)
    stale = await conn.fetch(
        "SELECT pc.citation_id::text AS cid, pc.citation_type, p.canonical_ref, w.canonical_id "
        "FROM free_will.passage_citations pc "
        "JOIN free_will.passages p ON p.passage_id = pc.passage_id "
        "JOIN free_will.ancient_works w ON w.work_id = p.work_id "
        "WHERE pc.kg_node_id = $1 AND w.canonical_id IN ($2, $3)",
        STALE_BOGUS_ARG_CITATION,
        TOPICA_CANONICAL,
        ORATOR_CANONICAL,
    )

    # Report
    per_arg: dict[str, int] = {}
    for p in to_create:
        per_arg[p["arg"]] = per_arg.get(p["arg"], 0) + 1
    print(f"Arguments to re-ground          : {len(REGROUND_PLAN)}")
    print(
        f"primary_source citations to add : {len(to_create)} (already present: {already})"
    )
    for arg in sorted(REGROUND_PLAN):
        spec = REGROUND_PLAN[arg]
        n = per_arg.get(arg, 0)
        sample = next((p["ref"] for p in to_create if p["arg"] == arg), "-")
        print(f"  {arg}")
        print(
            f"      work={spec['work'].rsplit('_', 2)[-2]}  new_cits={n}  e.g. ref {sample}  conf={spec['confidence']}"
        )
    print(f"\nArguments SKIPPED (no explicit Cicero locus): {len(SKIPPED_ARGS)}")
    for a, why in SKIPPED_ARGS.items():
        print(f"  {a}: {why}")
    if missing:
        print(f"\nLoci with NO genuine passage (skipped): {len(missing)}")
        for m in missing:
            print(f"  {m}")
    print(f"\nStale bogus arg-citations to delete: {len(stale)}")
    for s in stale:
        print(
            f"  {s['cid']} type={s['citation_type']} -> {s['canonical_id']} {s['canonical_ref']}"
        )

    snap = {
        "timestamp": ts,
        "phase": "A",
        "citations_to_create": to_create,
        "stale_bogus_deleted": [dict(s) for s in stale],
        "skipped_args": SKIPPED_ARGS,
        "missing_loci": missing,
    }
    (SNAPSHOT_DIR / "phase_a.json").write_text(
        json.dumps(snap, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    if commit:
        async with conn.transaction():
            for p in to_create:
                await conn.execute(
                    "INSERT INTO free_will.passage_citations "
                    "(passage_id, kg_node_id, citation_type, confidence, notes) "
                    "VALUES ($1::uuid, $2, 'primary_source', $3, $4)",
                    p["passage_id"],
                    p["arg"],
                    p["confidence"],
                    f"re-grounded {ts}: {p['note']} ref {p['ref']}",
                )
            for s in stale:
                await conn.execute(
                    "DELETE FROM free_will.passage_citations WHERE citation_id = $1::uuid",
                    s["cid"],
                )
        print(f"\nCOMMITTED Phase A: +{len(to_create)} citations, -{len(stale)} stale.")
    else:
        print("\n[DRY-RUN] Phase A: no DB changes.")

    return {
        "created": len(to_create),
        "already": already,
        "args": len(per_arg),
        "stale_deleted": len(stale),
        "missing": missing,
    }


# ---------------------------------------------------------------------------
# PHASE B
# ---------------------------------------------------------------------------
async def phase_b(conn: asyncpg.Connection, commit: bool, ts: str) -> dict:
    print("\n" + "=" * 70)
    print("PHASE B — delete fake passage-shells (DB + git mirror)")
    print("=" * 70)

    shells = await _shell_ids(conn)
    print(f"Shell nodes (DB): {len(shells)}")

    # Confirm no argument still depends on a shell via a non-structural relation
    # other than the cites_primary_source / evidenced_by we are about to delete.
    dep = await conn.fetch(
        "SELECT relation, count(*) c FROM free_will.kg_edges "
        "WHERE (source = ANY($1::text[]) OR target = ANY($1::text[])) "
        "GROUP BY relation ORDER BY relation",
        shells,
    )
    print("Shell edge relations (DB):")
    for d in dep:
        print(f"  {d['relation']}: {d['c']}")

    cit_n = await conn.fetchval(
        "SELECT count(*) FROM free_will.passage_citations WHERE kg_node_id = ANY($1::text[])",
        shells,
    )
    edge_n = await conn.fetchval(
        "SELECT count(*) FROM free_will.kg_edges WHERE source = ANY($1::text[]) OR target = ANY($1::text[])",
        shells,
    )
    print(
        f"\nDB to delete: passage_citations={cit_n}, kg_edges={edge_n}, kg_nodes={len(shells)}"
    )

    # Snapshot the exact rows
    cit_rows = [
        dict(r)
        for r in await conn.fetch(
            "SELECT citation_id::text, passage_id::text, kg_node_id, citation_type, confidence "
            "FROM free_will.passage_citations WHERE kg_node_id = ANY($1::text[])",
            shells,
        )
    ]
    edge_rows = [
        dict(r)
        for r in await conn.fetch(
            "SELECT edge_id::text, source, target, relation "
            "FROM free_will.kg_edges WHERE source = ANY($1::text[]) OR target = ANY($1::text[])",
            shells,
        )
    ]
    node_rows = [
        dict(r)
        for r in await conn.fetch(
            "SELECT node_id, id, label, type FROM free_will.kg_nodes WHERE node_id = ANY($1::text[])",
            shells,
        )
    ]
    (SNAPSHOT_DIR / "phase_b.json").write_text(
        json.dumps(
            {
                "timestamp": ts,
                "phase": "B",
                "shells": shells,
                "deleted_citations": cit_rows,
                "deleted_edges": edge_rows,
                "deleted_nodes": node_rows,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    # git mirror counts (dry-run preview = same predicate, commit=False)
    shell_set = set(shells)
    git_nodes_dropped = _remove_git_lines(
        NODES_PATH, lambda o: _git_node_id(o) in shell_set, commit
    )

    def _edge_touches_shell(o: dict) -> bool:
        s, t, _r = _git_edge_ends(o)
        return s in shell_set or t in shell_set

    git_edges_dropped = _remove_git_lines(
        EDGES_PATH,
        _edge_touches_shell,
        commit,
    )
    print(
        f"git mirror: nodes.jsonl drop={git_nodes_dropped}, edges.jsonl drop={git_edges_dropped}"
    )

    if commit:
        async with conn.transaction():
            await conn.execute(
                "DELETE FROM free_will.passage_citations WHERE kg_node_id = ANY($1::text[])",
                shells,
            )
            await conn.execute(
                "DELETE FROM free_will.kg_edges WHERE source = ANY($1::text[]) OR target = ANY($1::text[])",
                shells,
            )
            await conn.execute(
                "DELETE FROM free_will.kg_nodes WHERE node_id = ANY($1::text[])", shells
            )
        print(
            f"COMMITTED Phase B: -{cit_n} citations, -{edge_n} edges, -{len(shells)} nodes (DB) "
            f"+ git nodes -{git_nodes_dropped}, edges -{git_edges_dropped}."
        )
    else:
        print("[DRY-RUN] Phase B: no DB changes; git files NOT rewritten.")

    return {
        "db_citations": cit_n,
        "db_edges": edge_n,
        "db_nodes": len(shells),
        "git_nodes": git_nodes_dropped,
        "git_edges": git_edges_dropped,
    }


# ---------------------------------------------------------------------------
# PHASE C
# ---------------------------------------------------------------------------
async def phase_c(conn: asyncpg.Connection, commit: bool, ts: str) -> dict:
    print("\n" + "=" * 70)
    print("PHASE C — drop bogus Topica/Orator works")
    print("=" * 70)

    result: dict = {}
    for canon, label in ((TOPICA_CANONICAL, "Topica"), (ORATOR_CANONICAL, "Orator")):
        wid = await _work_id(conn, canon)
        if wid is None:
            print(f"  {label} ({canon}): already absent.")
            result[label] = {"present": False}
            continue
        n_pass = await conn.fetchval(
            "SELECT count(*) FROM free_will.passages WHERE work_id = $1::uuid", wid
        )
        n_cit = await conn.fetchval(
            "SELECT count(*) FROM free_will.passage_citations pc "
            "JOIN free_will.passages p ON p.passage_id = pc.passage_id "
            "WHERE p.work_id = $1::uuid",
            wid,
        )
        print(f"  {label} ({canon}): passages={n_pass}, remaining citations={n_cit}")
        if n_cit != 0:
            raise SystemExit(
                f"STOP: {label} ({canon}) still has {n_cit} passage_citations. "
                "Run Phase A + B first. Refusing to delete a work with live citations."
            )
        result[label] = {
            "present": True,
            "passages": n_pass,
            "remaining_citations": n_cit,
            "work_id": wid,
        }

    (SNAPSHOT_DIR / "phase_c.json").write_text(
        json.dumps(
            {"timestamp": ts, "phase": "C", "works": result},
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    if commit:
        async with conn.transaction():
            for label, info in result.items():
                if not info.get("present"):
                    continue
                wid = info["work_id"]
                await conn.execute(
                    "DELETE FROM free_will.passages WHERE work_id = $1::uuid", wid
                )
                await conn.execute(
                    "DELETE FROM free_will.ancient_works WHERE work_id = $1::uuid", wid
                )
                print(
                    f"  COMMITTED: deleted {label} ({info['passages']} passages + 1 work row)."
                )
    else:
        print("[DRY-RUN] Phase C: no DB changes.")

    return result


async def main(phase: str, commit: bool) -> int:
    import asyncpg

    SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
    ts = _stamp()
    print(f"Mode: {'COMMIT' if commit else 'DRY-RUN'}   Phase: {phase}   {ts}")

    conn = await asyncio.wait_for(asyncpg.connect(_pg_url(_db_url())), timeout=30)
    try:
        if phase in ("A", "all"):
            await phase_a(conn, commit, ts)
        if phase in ("B", "all"):
            await phase_b(conn, commit, ts)
        if phase in ("C", "all"):
            await phase_c(conn, commit, ts)
    finally:
        await conn.close()
    if not commit:
        print("\n[DRY-RUN] Pass --commit to apply.")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--phase", choices=["A", "B", "C", "all"], default="all")
    ap.add_argument(
        "--commit", action="store_true", help="Write changes (default: dry-run)"
    )
    args = ap.parse_args()
    raise SystemExit(asyncio.run(main(args.phase, args.commit)))
